
apiVersion: v1
kind: ServiceAccount
metadata:
  name: graylog
  namespace: graylog
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: graylog
  namespace: graylog
rules:
- apiGroups:
    - ""
  resources:
    - pods
    - secrets
  verbs:
    - get
    - list
    - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: graylog
  namespace: graylog
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: graylog
subjects:
- kind: ServiceAccount
  name: graylog