apiVersion: v1
kind: Secret
metadata:
  name: graylog-web-tls
  namespace: graylog 
data:
  tls.crt: --<GRAYLOG-INGRESS-TLS-CRT>--
  tls.key: --<GRAYLOG-INGRESS-TLS-KEY>--
type: kubernetes.io/tls

---

apiVersion: v1
kind: Secret
metadata:
  name: graylog
  namespace: graylog
type: Opaque
data:
  graylog-root-username: "YWRtaW4="
  graylog-password-secret: --<GRAYLOG-ADMIN-PASSWORD>--
  graylog-password-sha2: --<GRAYLOG-ADMIN-PASSWORD-SHA2-256>--
---